# Generated by Django 3.0 on 2020-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_optimization', '0002_auto_20200425_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='vegetarian',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
